### ISSUE TITLE
Questions about the Metrictor_PPI function

### ISSUE THREAD

**Issue by wan-nie** [zqgao22/HIGH-PPI#2]
I would like to express my gratitude for making the code open-source. I have a question regarding the `Metrictor_PPI` function in [HIGH-PPI/utils.py](https://github.com/zqgao22/HIGH-PPI/blob/main/utils.py) and I was hoping you could assist me.

- It seems that the arguments of the sklearn `precision_recall_curve` function are reversed. Could you kindly clarify if this is the case?
- `self.pre` is (0,1) label instead of the predicted probability $P(y=1)$. Line 150 in [HIGH-PPI/model_train.py](https://github.com/zqgao22/HIGH-PPI/blob/main/model_train.py). I am concerned that this could affect the correctness of AURPC.

**Comment by zqgao22** [comment]
Hi, Wan. Thank you very much for pointing this issue. You are right. For Sklearn's `precision_recall_curve` function, we need to take the predicted probability as the second entry.
In fact, the result of our source data is calculated with a simpler function `average_precision_score`, which also requires the predicted probability scores. However, we later tried to rewrite it to a more widely used `precision_recall_curve` function and ignored the above problem. We are about to modify it to the correct form.

**Comment by wan-nie** [comment]
Hi, Ziqi. Thank you for the prompt reply. As the results were correctly calculated using the predicted probability, I think this issue can be closed now.
